from .models import (
    AdmissionPlace,
    Department,
    EducationalProgram,
    EntranceRequirement,
    Faculty,
    HistoricalPassingScore,
    Major,
    PlanFile,
    PracticePartner,
    SourceProvenance,
    SourceObservation,
    StudyPlan,
    TuitionOption,
)

__all__ = [
    "AdmissionPlace",
    "Department",
    "EducationalProgram",
    "EntranceRequirement",
    "Faculty",
    "HistoricalPassingScore",
    "Major",
    "PlanFile",
    "PracticePartner",
    "SourceProvenance",
    "SourceObservation",
    "StudyPlan",
    "TuitionOption",
]
